In [1]:
import geopandas as gpd

In [2]:
gdf = gpd.read_file("data/Predicciones/mapa_continuo.gpkg")
gdf

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,microplastics_log_est,microplastics_est,geometry
0,-78.0,-175.5,543.707048,-1.775068,34.395912,1.680748,27.419722,1.907441,311.153168,59.152695,0.211114,0.235053,POINT (-175.5 -78)
1,-78.0,-175.0,533.294654,-1.775068,34.395912,1.243596,27.419722,1.907441,311.153168,59.152695,0.210195,0.233919,POINT (-175 -78)
2,-78.0,-173.0,543.143622,-1.808737,34.373737,-0.760849,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,POINT (-173 -78)
3,-78.0,-172.5,540.559218,-1.808737,34.373737,-0.805667,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,POINT (-172.5 -78)
4,-78.0,-172.0,535.905487,-1.808737,34.373737,-0.708566,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,POINT (-172 -78)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127008,72.0,-15.0,425.634963,0.289420,34.764435,0.504466,11.316046,0.823883,318.571198,32.765865,0.315589,0.371066,POINT (-15 72)
127009,72.0,25.5,94.266326,6.833642,34.894951,0.065487,6.138589,0.608244,298.023193,4.414944,0.395133,0.484582,POINT (25.5 72)
127010,72.0,26.5,110.341777,6.723017,34.888157,0.365244,5.862425,0.607004,298.572815,4.962784,0.355206,0.426474,POINT (26.5 72)
127011,72.0,27.0,111.642511,6.723017,34.888157,-0.597254,5.862425,0.607004,298.572815,4.962784,0.331746,0.393399,POINT (27 72)
127012,72.0,27.5,98.314809,6.519808,34.888569,-0.687283,5.836751,0.615934,299.227234,5.952769,0.316624,0.372486,POINT (27.5 72)

In [4]:
gdf_profile = gpd.read_file("data/grid_ocean/grilla_agua_perfiles.gpkg")
gdf_profile

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,cluster_num,profile_eco,geometry
0,-78.0,-175.5,543.707048,-1.775068,34.395912,1.680748,27.419722,1.907441,311.153168,59.152695,5,cold_open_sea,POINT (-175.5 -78)
1,-78.0,-175.0,533.294654,-1.775068,34.395912,1.243596,27.419722,1.907441,311.153168,59.152695,5,cold_open_sea,POINT (-175 -78)
2,-78.0,-173.0,543.143622,-1.808737,34.373737,-0.760849,27.574869,1.912899,312.213226,57.888039,5,cold_open_sea,POINT (-173 -78)
3,-78.0,-172.5,540.559218,-1.808737,34.373737,-0.805667,27.574869,1.912899,312.213226,57.888039,5,cold_open_sea,POINT (-172.5 -78)
4,-78.0,-172.0,535.905487,-1.808737,34.373737,-0.708566,27.574869,1.912899,312.213226,57.888039,5,cold_open_sea,POINT (-172 -78)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127006,72.0,-15.0,425.634963,0.289420,34.764435,0.504466,11.316046,0.823883,318.571198,32.765865,1,cold_shelf,POINT (-15 72)
127007,72.0,25.5,94.266326,6.833642,34.894951,0.065487,6.138589,0.608244,298.023193,4.414944,1,cold_shelf,POINT (25.5 72)
127008,72.0,26.5,110.341777,6.723017,34.888157,0.365244,5.862425,0.607004,298.572815,4.962784,1,cold_shelf,POINT (26.5 72)
127009,72.0,27.0,111.642511,6.723017,34.888157,-0.597254,5.862425,0.607004,298.572815,4.962784,1,cold_shelf,POINT (27 72)
127010,72.0,27.5,98.314809,6.519808,34.888569,-0.687283,5.836751,0.615934,299.227234,5.952769,1,cold_shelf,POINT (27.5 72)

In [3]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 127013 entries, 0 to 127012
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   lat                    127013 non-null  float64
 1   lon                    127013 non-null  float64
 2   distance_to_coast_km   127013 non-null  float64
 3   temperature            127013 non-null  float32
 4   salinity               127013 non-null  float32
 5   chlorophyll            127013 non-null  float32
 6   nitrate                127013 non-null  float32
 7   phosphate              127013 non-null  float32
 8   oxygen_dissolved       127013 non-null  float32
 9   oxygen_utilization     127013 non-null  float32
 10  microplastics_log_est  127013 non-null  float64
 11  microplastics_est      127013 non-null  float64
 12  geometry               127013 non-null  geometry
dtypes: float32(7), float64(5), geometry(1)
memory usage: 9.2 MB

In [5]:
gdf_profile.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 127011 entries, 0 to 127010
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   lat                   127011 non-null  float64
 1   lon                   127011 non-null  float64
 2   distance_to_coast_km  127011 non-null  float64
 3   temperature           127011 non-null  float32
 4   salinity              127011 non-null  float32
 5   chlorophyll           127011 non-null  float32
 6   nitrate               127011 non-null  float32
 7   phosphate             127011 non-null  float32
 8   oxygen_dissolved      127011 non-null  float32
 9   oxygen_utilization    127011 non-null  float32
 10  cluster_num           127011 non-null  int32
 11  profile_eco           127011 non-null  object
 12  geometry              127011 non-null  geometry
dtypes: float32(7), float64(3), geometry(1), int32(1), object(1)
memory usage: 8.7+ MB

In [6]:
gdf = gdf.to_crs(gdf_profile.crs)

gdf = gpd.sjoin(
    gdf,
    gdf_profile[["geometry", "profile_eco"]],
    how="left",
    predicate="intersects",
)

gdf = gdf.drop(columns=["index_right"])
gdf

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,microplastics_log_est,microplastics_est,geometry,profile_eco
0,-78.0,-175.5,543.707048,-1.775068,34.395912,1.680748,27.419722,1.907441,311.153168,59.152695,0.211114,0.235053,POINT (-175.5 -78),cold_open_sea
1,-78.0,-175.0,533.294654,-1.775068,34.395912,1.243596,27.419722,1.907441,311.153168,59.152695,0.210195,0.233919,POINT (-175 -78),cold_open_sea
2,-78.0,-173.0,543.143622,-1.808737,34.373737,-0.760849,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,POINT (-173 -78),cold_open_sea
3,-78.0,-172.5,540.559218,-1.808737,34.373737,-0.805667,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,POINT (-172.5 -78),cold_open_sea
4,-78.0,-172.0,535.905487,-1.808737,34.373737,-0.708566,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,POINT (-172 -78),cold_open_sea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127008,72.0,-15.0,425.634963,0.289420,34.764435,0.504466,11.316046,0.823883,318.571198,32.765865,0.315589,0.371066,POINT (-15 72),cold_shelf
127009,72.0,25.5,94.266326,6.833642,34.894951,0.065487,6.138589,0.608244,298.023193,4.414944,0.395133,0.484582,POINT (25.5 72),cold_shelf
127010,72.0,26.5,110.341777,6.723017,34.888157,0.365244,5.862425,0.607004,298.572815,4.962784,0.355206,0.426474,POINT (26.5 72),cold_shelf
127011,72.0,27.0,111.642511,6.723017,34.888157,-0.597254,5.862425,0.607004,298.572815,4.962784,0.331746,0.393399,POINT (27 72),cold_shelf
127012,72.0,27.5,98.314809,6.519808,34.888569,-0.687283,5.836751,0.615934,299.227234,5.952769,0.316624,0.372486,POINT (27.5 72),cold_shelf

In [7]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 127013 entries, 0 to 127012
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   lat                    127013 non-null  float64
 1   lon                    127013 non-null  float64
 2   distance_to_coast_km   127013 non-null  float64
 3   temperature            127013 non-null  float32
 4   salinity               127013 non-null  float32
 5   chlorophyll            127013 non-null  float32
 6   nitrate                127013 non-null  float32
 7   phosphate              127013 non-null  float32
 8   oxygen_dissolved       127013 non-null  float32
 9   oxygen_utilization     127013 non-null  float32
 10  microplastics_log_est  127013 non-null  float64
 11  microplastics_est      127013 non-null  float64
 12  geometry               127013 non-null  geometry
 13  profile_eco            127011 non-null  object
dtypes: float32(7), float64(5), geometry(1), object(1)
memory usage: 11.1+ MB

In [8]:
gdf.to_file(
    "data/Predicciones/mapa_continuo.gpkg",
    driver="GPKG"
)